### PR TITLE
use Resque's queue_from_class method to determine queu

### PR DESCRIPTION
**Pull request by jdoconnor**
@zvkemp

### CODE REVIEW

**Comment by zvkemp** [comment]
:ok:

**Comment by camertron** [comment]
Oh now _that's_ handy. :+1:

**Comment by camertron** [comment]
Although, it looks like `queue_from_class` is returning `false` for the test job for some reason, which is causing tests to fail.

**Comment by jdoconnor** [comment]
yep. working on that.

**Comment by jdoconnor** [comment]
fixed test and added another. The Resque functionality wasn't going to do it in this case, so I added a method

**Comment by camertron** [comment]
Ah ok. Looks good :+1:

**Pull request merged**
